### PR TITLE
Operation Environment

### PR DESCRIPTION
**Pull request by npalacio**

### CODE REVIEW

**Review by jburr9 — COMMENTED** [review]
@npalacio, scenario description looks great! Just two quick questions:

1. Is it _Elastic**S**earch_ or _Elastic**s**earch_? I did the second one because that's how I saw it referenced in their repo and website. Doesn't matter to me but we should probably be consistent.
2. Do you plan to include the diagram directly in the final Proposal markdown document? I was expecting to see it included in the OperationEnvironment.md but if you planned to do it later, looks good!

**Comment by amdorsey12** [comment]
Looks good overall, just a few things:
I'd change ```specifically a bank.``` to ```for example a bank```. 
```make unusable the ElasticSearch data.``` to ```make the Elasticsearch data unusable```.

Finally are we actually gonna talk about a customer facing app, i.e. a customer banking app for their transactions, or just the enterprise business facing app?

**Comment by npalacio** [comment]
@jburr9 1. You are correct, let me update all those to Elasticsearch. 2. I plan on using the picture in the final .MD document, just didnt do it on this one.

**Comment by npalacio** [comment]
@amdorsey12 I will update those phrases and my understanding was we are sticking with just the enterprise business facing app for now but could add that other stuff down the line.

**Review by amdorsey12 — APPROVED** [review]
Looks good

**Pull request merged**
